version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./app/uploads:/app/uploads
      - ./app/analysis:/app/analysis
      - cache_volume:/app/cache
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auditoria_ia
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      - HF_DATASETS_CACHE=/app/cache
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auditoria_ia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  cache_volume:
