services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./fastapi-app/main.py:/app/main.py
      - ./uploads:/app/uploads
      - ./analysis:/app/analysis
    environment:
      - DATABASE_URL=postgresql://postgres:Nods2025!@db:5432/auditoria_ia
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=auditoria_ia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nods2025!
    ports:
      - "5432:5432"

volumes:
  postgres_data:
