version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./analysis:/app/analysis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auditoria_ia
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auditoria_ia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
